export { default as getArticlesType } from './get.articlesType'
export { default as getArticles } from './get.articles'
export { default as getArticle } from './get.article'
export { default as getAbout } from './get.about'
export { default as getWebgraphy } from './get.webgraphy'